export const QUESTIONS = [
	{
		id: 1,
		question: 'O que é uma variável?',
		options: ['Um tipo de dado fixo', 'Um espaço na memória para armazenar valores', 'Um comando de repetição'],
		correctAnswer: 1,
	},
	{
		id: 2,
		question: 'Qual símbolo é usado para comentários em JavaScript?',
		options: ['#', '//', '<!-- -->'],
		correctAnswer: 1,
	},
	{
		id: 3,
		question: 'Qual destes é um tipo de dado primitivo em JavaScript?',
		options: ['Object', 'Number', 'Array'],
		correctAnswer: 1,
	},
	{
		id: 4,
		question: 'O que significa HTML?',
		options: ['HyperText Markup Language', 'HighText Machine Language', 'Hyperlinks and Text Markup Language'],
		correctAnswer: 0,
	},
	{
		id: 5,
		question: 'Qual tag é usada para criar um link em HTML?',
		options: ['<a>', '<link>', '<href>'],
		correctAnswer: 0,
	},
	{
		id: 6,
		question: 'Qual comando exibe uma mensagem no console em JavaScript?',
		options: ['alert()', 'console.log()', 'print()'],
		correctAnswer: 1,
	},
	{
		id: 7,
		question: 'Qual estrutura é usada para repetir instruções várias vezes?',
		options: ['if', 'loop', 'for'],
		correctAnswer: 2,
	},
	{
		id: 8,
		question: 'Qual destes operadores é usado para comparação de igualdade em valor e tipo em JavaScript?',
		options: ['==', '=', '==='],
		correctAnswer: 2,
	},
	{
		id: 9,
		question: 'O que é uma função?',
		options: ['Um laço de repetição', 'Um bloco de código reutilizável', 'Um tipo de variável'],
		correctAnswer: 1,
	},
	{
		id: 10,
		question: 'Qual linguagem é usada para estilizar páginas web?',
		options: ['HTML', 'CSS', 'Python'],
		correctAnswer: 1,
	},
	{
		id: 11,
		question: 'O que significa CSS?',
		options: ['Colorful Style Sheets', 'Cascading Style Sheets', 'Creative Style System'],
		correctAnswer: 1,
	},
	{
		id: 12,
		question: 'Em qual linguagem usamos o comando “print()”?',
		options: ['Python', 'JavaScript', 'HTML'],
		correctAnswer: 0,
	},
	{
		id: 13,
		question: 'O que é um array?',
		options: ['Uma variável que guarda múltiplos valores', 'Um tipo de laço', 'Um erro de sintaxe'],
		correctAnswer: 0,
	},
	{
		id: 14,
		question: 'Qual método adiciona um item ao final de um array em JavaScript?',
		options: ['push()', 'add()', 'append()'],
		correctAnswer: 0,
	},
	{
		id: 15,
		question: 'O que significa a sigla API?',
		options: ['Application Programming Interface', 'Advanced Program Integration', 'Automatic Process Interaction'],
		correctAnswer: 0,
	},
	{
		id: 16,
		question: 'Qual comando é usado para criar uma variável em JavaScript?',
		options: ['var', 'int', 'define'],
		correctAnswer: 0,
	},
	{
		id: 17,
		question: 'Em qual linguagem usamos o comando “def” para definir funções?',
		options: ['JavaScript', 'Python', 'C++'],
		correctAnswer: 1,
	},
	{
		id: 18,
		question: 'Qual estrutura é usada para decisões condicionais?',
		options: ['loop', 'if/else', 'for'],
		correctAnswer: 1,
	},
	{
		id: 19,
		question: 'O que é um bug?',
		options: ['Um erro no código', 'Um tipo de função', 'Um componente visual'],
		correctAnswer: 0,
	},
	{
		id: 20,
		question: 'Qual dessas opções representa um booleano?',
		options: ['true/false', '0/1', '“verdadeiro”/“falso”'],
		correctAnswer: 0,
	},
	{
		id: 21,
		question: 'O que é o Node.js?',
		options: ['Um framework front-end', 'Um ambiente para rodar JavaScript no servidor', 'Um banco de dados'],
		correctAnswer: 1,
	},
	{
		id: 22,
		question: 'Qual destes bancos de dados é relacional?',
		options: ['MongoDB', 'PostgreSQL', 'Redis'],
		correctAnswer: 1,
	},
	{
		id: 23,
		question: 'O que significa JSON?',
		options: ['JavaScript Object Notation', 'Java Syntax Oriented Network', 'Java Source Object Name'],
		correctAnswer: 0,
	},
	{
		id: 24,
		question: 'Qual método converte um objeto em string JSON?',
		options: ['JSON.parse()', 'JSON.stringify()', 'toString()'],
		correctAnswer: 1,
	},
	{
		id: 25,
		question: 'O que faz o comando “git clone”?',
		options: ['Cria um repositório novo', 'Baixa um repositório existente', 'Remove um repositório'],
		correctAnswer: 1,
	},
	{
		id: 26,
		question: 'Qual comando é usado para inicializar um repositório Git?',
		options: ['git start', 'git init', 'git new'],
		correctAnswer: 1,
	},
	{
		id: 27,
		question: 'O que é um commit no Git?',
		options: ['Uma versão salva do projeto', 'Um erro no repositório', 'Uma branch temporária'],
		correctAnswer: 0,
	},
	{
		id: 28,
		question: 'O que significa “front-end”?',
		options: ['Parte do servidor', 'Parte visível ao usuário', 'Banco de dados'],
		correctAnswer: 1,
	},
	{
		id: 29,
		question: 'O que significa “back-end”?',
		options: ['Interface gráfica', 'Lógica e banco de dados', 'Design do site'],
		correctAnswer: 1,
	},
	{
		id: 30,
		question: 'O que é um framework?',
		options: ['Uma linguagem', 'Um conjunto de ferramentas e padrões para desenvolvimento', 'Um tipo de variável'],
		correctAnswer: 1,
	},
	{
		id: 31,
		question: 'Qual comando instala pacotes no Node.js?',
		options: ['install-node', 'npm install', 'node add'],
		correctAnswer: 1,
	},
	{
		id: 32,
		question: 'Qual destas tecnologias é usada para criar interfaces de usuário reativas?',
		options: ['React', 'MySQL', 'Express'],
		correctAnswer: 0,
	},
	{
		id: 33,
		question: 'O que o hook useEffect faz no React?',
		options: ['Gerencia estado', 'Executa efeitos colaterais', 'Define rotas'],
		correctAnswer: 1,
	},
	{
		id: 34,
		question: 'O que significa “null” em programação?',
		options: ['Um erro de tipo', 'Ausência intencional de valor', 'Um número zero'],
		correctAnswer: 1,
	},
	{
		id: 35,
		question: 'Qual operador é usado para concatenar strings em JavaScript?',
		options: ['+', '&', '.'],
		correctAnswer: 0,
	},
	{
		id: 36,
		question: 'Qual comando limpa o terminal?',
		options: ['clear', 'cls', 'reset'],
		correctAnswer: 0,
	},
	{
		id: 37,
		question: 'Qual é a extensão padrão de arquivos JavaScript?',
		options: ['.js', '.jsx', '.ts'],
		correctAnswer: 0,
	},
	{
		id: 38,
		question: 'O que faz o comando return em uma função?',
		options: ['Sai da função e retorna um valor', 'Reinicia o código', 'Chama outra função'],
		correctAnswer: 0,
	},
	{
		id: 39,
		question: 'O que é uma constante em programação?',
		options: ['Um valor que pode mudar', 'Um valor fixo após declarado', 'Uma variável temporária'],
		correctAnswer: 1,
	},
	{
		id: 40,
		question: 'O que é um loop infinito?',
		options: ['Um laço que nunca termina', 'Um erro de compilação', 'Um array com muitos itens'],
		correctAnswer: 0,
	},
	{
		id: 41,
		question: 'Qual destes é um operador lógico?',
		options: ['+', '&&', '='],
		correctAnswer: 1,
	},
	{
		id: 42,
		question: 'Qual comando é usado para importar módulos em JavaScript moderno?',
		options: ['require()', 'import', 'include'],
		correctAnswer: 1,
	},
	{
		id: 43,
		question: 'O que é um objeto em JavaScript?',
		options: ['Um conjunto de pares chave-valor', 'Um tipo de número', 'Um elemento HTML'],
		correctAnswer: 0,
	},
	{
		id: 44,
		question: 'Qual método remove o último elemento de um array?',
		options: ['pop()', 'shift()', 'slice()'],
		correctAnswer: 0,
	},
	{
		id: 45,
		question: 'Qual desses é um framework backend em Node.js?',
		options: ['Express', 'Vue', 'Tailwind'],
		correctAnswer: 0,
	},
	{
		id: 46,
		question: 'Qual é a principal função do banco de dados?',
		options: ['Renderizar páginas', 'Armazenar e gerenciar dados', 'Rodar o código da aplicação'],
		correctAnswer: 1,
	},
	{
		id: 47,
		question: 'Qual é o resultado de typeof "123"?',
		options: ['number', 'string', 'integer'],
		correctAnswer: 1,
	},
	{
		id: 48,
		question: 'O que é uma IDE?',
		options: ['Interface de Desenvolvimento Integrado', 'Internet Development Engine', 'Internal Data Editor'],
		correctAnswer: 0,
	},
	{
		id: 49,
		question: 'Qual destes é um operador de atribuição?',
		options: ['==', '=', '==='],
		correctAnswer: 1,
	},
	{
		id: 50,
		question: 'O que significa “open source”?',
		options: ['Software fechado', 'Código aberto e público', 'Software pago'],
		correctAnswer: 1,
	},
];
